export enum CertificateErrorCode {
  CERTIFICATE_NOT_FOUND = 'CERTIFICATE_NOT_FOUND',
  CERTIFICATE_ALREADY_REVOKED = 'CERTIFICATE_ALREADY_REVOKED',
  CERTIFICATE_EXPIRED = 'CERTIFICATE_EXPIRED',
  CERTIFICATE_DUPLICATE = 'CERTIFICATE_DUPLICATE',
  CERTIFICATE_VERIFICATION_FAILED = 'CERTIFICATE_VERIFICATION_FAILED',
  STELLAR_TRANSACTION_FAILED = 'STELLAR_TRANSACTION_FAILED',
  INVALID_STELLAR_ADDRESS = 'INVALID_STELLAR_ADDRESS',
  UNAUTHORIZED_REVOCATION = 'UNAUTHORIZED_REVOCATION',
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  CERTIFICATE_INACTIVE = 'CERTIFICATE_INACTIVE',
}
